name: Build application
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: oliverlinux/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: oliverlinux/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
