name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
         submodules: 'recursive'
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
         name: artifact
         path: /a/
      - name: Create release
        id: create_release
        uses: actions/action-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /a/artifact.zip
          asset_name: artifact.zip
          asset_content_type: application/zip